### ISSUE TITLE
Could we replace Finish() with Flush inside glBindFramebuffer()?

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#27]
Could we replace `Finish()` with `Flush()` in the case of `glBindFramebuffer()`?
What extent does `Finish()` affect the performance? 

https://github.com/Think-Silicon/GLOVE/blob/1928c113853722cd97802d1a88ca109815d38c1e/GLES/source/context/contextFrameBuffer.cpp#L52

**Comment by abasilak** [comment]
The current rendering implementation is based on a framebuffer-state machine mechanism. Each draw call(s) must be ended by a `Context::Finish()` function (which in our case also corresponds to the `glFinish()` function) in order to submit and execute the active command buffer list and afterwards cleanup the caches.

Regarding your question, the answer is no! 
We can't move to a new framebuffer without waiting for the previous command list to be completed since it may need the previous framebuffer's attachment (color, depth or stencil) as shader input (texture sampler). 

Note that we have not investigate any alternatives that will boost performance for specific cases. 
Thus, there is room for improvement here.

**Comment by Michael-Lfx** [comment]
I have tested that is nothing harm to remove `glFinish()` inside the `glBindFramebuffer()` for the case that `draw to FBO1; FBO1's color attachment as input to FBO2;` when using the same program instance. I will make a more complex test case to find out whether it can handle all the use case without `glFinish()`.
