### ISSUE TITLE
Migrate to macOS/iOS stuck by VK_KHR_display

### ISSUE THREAD

**Issue by Michael-Lfx** [Think-Silicon/GLOVE#71]
As discussed in https://github.com/Think-Silicon/GLOVE/issues/69#issuecomment-493441027

I tried to run the project with Xcode on macOS 10.13.5 and got a few problems. One of the major problems was `VK_KHR_display`. I had to comment out `SetPlatformCallbacks()` because both [MoltenVK](https://github.com/KhronosGroup/MoltenVK) and [gfx-hal](https://github.com/gfx-rs/portability) did not implemented the following vk functions. 

https://github.com/Think-Silicon/GLOVE/blob/c13b36c40abfb18b2b482c0708ce0fc9fb961634/EGL/source/platform/vulkan/WSIPlaneDisplay.cpp#L53-L54

I got a crash within `Context::InitializeFrameBuffer()` who was calling `tex->CreateVkImageView();` through a null `mVkImageView` finally.

A out of topic question is that will you consider using some new language such as [Rust](https://www.rust-lang.org) to write the project. They offer some features to simplify project management, cross compilation and dependency management. 

cc @dgeorg79

**Comment by dgeorg79** [comment]
Sorry for the delay, pretty busy here.

It is expected GLOVE not to work on macOS/iOS, since it currently supports ONLY Linux XCB & Android Windows Platforms. 

To test GLOVE on macOS you should create a new EGL platform backend for macOS on GLOVE/ EGL.

Please read instructions on how to create a new EGL backend [in GLOVE Design doc](https://github.com/Think-Silicon/GLOVE/blob/master/Docs/GLOVEDesignDocument.md#212-egl-back-end-platform-support). 

Instructions on how to use WSI for macOS can be found in [Vulkan spec](https://renderdoc.org/vkspec_chunked/chap32.html#platformCreateSurface_macos).

Please be also aware that most probably you should protect pieces of code under **VK_USE_PLATFORM_MACOS_MVK** flag, like we already do for **VK_USE_PLATFORM_XCB_KHR** in source code + several CMakeLists.txt.

Last but not least, do not forget to activate desired Vulkan extensions in [GLES/ Vulkan Context](https://github.com/Think-Silicon/GLOVE/blob/master/GLES/source/vulkan/context.cpp#L36).

Would you like to give it a try? We are here to support! :smile:

**Comment by Michael-Lfx** [comment]
Thank you for the instructions. My colleague and I will discuss tomorrow in detail. We prefer to use Rust language currently.

**Comment by dgeorg79** [comment]
Again, sorry for the delay :disappointed:

Rust Language is interesting, however GLOVE is an already mature project written in C/C++. Writing some modules in Rust would complicate things a lot. 

I recently added WAYLAND support in GLOVE (see commit 605394dbe6512c70b82d9a93eb990203f20e9947). I believe macOS support would look similar to this, you could check.

**Comment by Michael-Lfx** [comment]
Good to know. Nice work! Please take some time to review my PRs. :)

**Comment by dgeorg79** [comment]
GLOVE porting to MacOS/iOS would be really nice! Therefore, I spent some time to construct the EGL backend for MacOS platform (see bab6c97d59311468bb332c92371aadc7aaae2a9e). Of course the front-end is missing (creating NSView and passing it to eglCreateWindowSurface()) since I'm not familiar with Apple way of doing things. However, I believe that GLOVE porting to OSX is now much closer to reality. I would be more than happy if someone could complete this!

Moreover, I added the possibilty to try XCB backend under OSX (previously this option was activated only for Linux system).

To try XCB platform set use-surface to XCB, otherwise set use-surface to MACOS.

**Comment by Michael-Lfx** [comment]
The current EGL codebase is still difficult to understand such as `Display` and `DisplayDriver` should merge together because they are functionality alike.

**Comment by dgeorg79** [comment]
You're right, SW design in this part of code is a bit complicated, but this comes from the [EGL spec](https://www.khronos.org/registry/EGL/specs/eglspec.1.4.pdf). What complicates things is that EGLDisplay handles are life-time valid objects. As stated in the following extract from EGL spec (chapter 3.2), when calling eglTerminate(), all resources associated to this display (bound to `DisplayDriver` in GLOVE implementation) are released, but the EGLDisplay handle remains valid. This is the reason why `EGLDisplay_t` and `DisplayDriver` are separated.
  
```
Termination marks all EGL-specific resources, such as contexts and surfaces, 
associated with the specified display for deletion. 
Handles to all such resources are invalid as soon as eglTerminate returns, 
but the dpy handle itself remains valid
```

**Comment by Michael-Lfx** [comment]
Should we simplify this because we are implement EGL/GLES on top of Vulkan. There are already some  overhead. Maybe it's better to make it as thin as possible.

**Comment by dgeorg79** [comment]
We cannot simplify EGL codebase, since GLOVE aims to pass KHRONOS Conformance, therefore it has to cover all of cases mentioned in [EGL spec](https://www.khronos.org/registry/EGL/specs/eglspec.1.4.pdf).

However, I think that EGLDisplay related code can be simplified. I will try to make a quick refactoring

**Comment by Michael-Lfx** [comment]
I know little about KHRONOS Conformance. Why is it so important？I think Apple often violates the spec when they implement GLES.

**Comment by dgeorg79** [comment]
Think Silicon aims to officially support OpenGL ES 2.0, therefore GLOVE has to be KHRONOS conformant. KHRONOS Conformance tests certificate that an OpenGL ES 2.0 implementation is aligned to OpenGL ES 2.0 spec.

**Comment by kruglinski** [comment]
I think use GLOVE as front-end and [bgfx](https://github.com/bkaradzic/bgfx) as back-end would be very cool thing..

The design of GLOVE are very pretty, and rendering api wrap of bgfx are very thin, if we bring these two project together that would make GLOVE a gles 2 layer for almost every mainstream rendering api.

The only problem remaining is how to manage window surface, this is specific to platform, I think libSDL maybe a choice

**Comment by dgeorg79** [comment]
closed with release GLOVE v0.4

**Comment by Xioor** [comment]
@dgeorg79 Is iOS now supported on GLOVE?

**Comment by dgeorg79** [comment]
No, macOS is supported so far. Are you interested in iOS?

**Comment by Xioor** [comment]
@dgeorg79 Yes iOS support would be great!

**Comment by Xioor** [comment]
@dgeorg79 Also tvOS would be great if possible!

**Comment by WesleyKhoiVo** [comment]
Hi, Is there any new news?

**Comment by WesleyKhoiVo** [comment]
Hi, Is there any new news related iOS?

**Comment by dgeorg79** [comment]
This requires some amount of work, so I just opened a new issue for this (#93). Please follow the progress of the latter.
