### ISSUE TITLE
RFC: Why not ANGLE? Why GLOVE?

### ISSUE THREAD

**Issue by mick-p1982** [Think-Silicon/GLOVE#90]
Sorry guys, I'm just curious to hear what are your selling points versus ANGLE?

**Comment by dgeorg79** [comment]
Hi, 

   Sorry for the delay! 

I don't consider GLOVE as a competitive software to ANGLE, since GLOVE was originally designed to support OpenGL ES 2.0 in low-end devices with restricted resources. However, since it offers a nice & compact solution to run OpenGL ES on top of Vulkan, we open sourced it so that other people can try GLOVE in other systems as well.

We would be more than happy to receive feedback from the community regarding testing / usage of  GLOVE in other systems (e.g. Windows or Apple devices)
